# Generated by Django 6.0.4 on 2026-04-23 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'uploaded_at'], name='main_docume_user_id_cd249e_idx'),
        ),
        migrations.AddField(
            model_name='token',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.document'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['word'], name='main_token_word_13aa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['document', 'position'], name='main_token_documen_82364d_idx'),
        ),
    ]
