# Generated by Django 6.0.4 on 2026-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_token_document_created_at_document_token_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='token',
            name='main_token_documen_82364d_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='token_count_corrected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='mode',
            field=models.CharField(choices=[('original', 'Original'), ('corrected', 'Corrected')], default='original', max_length=10),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['document', 'mode', 'position'], name='main_token_documen_223e5b_idx'),
        ),
    ]
