# Generated by Django 6.0.4 on 2026-09-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_legacy_corpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='tokenized_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tokenizer_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='word',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='word_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.wordtype'),
        ),
        migrations.CreateModel(
            name='DocumentNgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.SmallIntegerField()),
                ('word_type_ids', models.JSONField()),
                ('mode', models.CharField(choices=[('original', 'Original'), ('corrected', 'Corrected')], max_length=10)),
                ('count', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngram_freqs', to='main.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'n', 'mode'], name='main_docume_documen_bcb01c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentWordFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('original', 'Original'), ('corrected', 'Corrected')], max_length=10)),
                ('count', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_freqs', to='main.document')),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wordtype')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'mode'], name='main_docume_documen_0d76c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'word_type', 'mode'), name='uniq_doc_wordfreq')],
            },
        ),
    ]
