# Generated by Django 6.0.4 on 2026-09-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_backfill_wordtype'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='token',
            name='main_token_word_13aa7e_idx',
        ),
        migrations.AlterField(
            model_name='token',
            name='word_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.wordtype'),
        ),
        migrations.RemoveField(
            model_name='token',
            name='word',
        ),
    ]
