# Generated by Django 6.0.4 on 2026-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_document_content_hash_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public corpora are visible to every registered user. Private corpora are visible only to admins.'),
        ),
    ]
