# Generated by Django 6.0.4 on 2026-09-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_corpus_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTaxonomyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('gloss', models.TextField(blank=True)),
                ('is_leaf', models.BooleanField(default=False)),
                ('top_category', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.errortaxonomynode')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_features', models.CharField(max_length=255)),
                ('source_segment_id', models.CharField(blank=True, max_length=50)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('original_text', models.TextField()),
                ('correction_text', models.TextField(blank=True)),
                ('state', models.CharField(default='active', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_annotations', to='main.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.errorannotation')),
                ('taxonomy_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='main.errortaxonomynode')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'taxonomy_node'], name='main_errora_documen_b1b859_idx'), models.Index(fields=['document', 'start_position'], name='main_errora_documen_95f24a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentErrorFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_freqs', to='main.document')),
                ('taxonomy_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.errortaxonomynode')),
            ],
            options={
                'indexes': [models.Index(fields=['document'], name='main_docume_documen_9a6450_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'taxonomy_node'), name='uniq_doc_errorfreq')],
            },
        ),
    ]
