# Generated by Django 6.0.4 on 2026-10-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=200)),
                ('match_key', models.CharField(max_length=200, unique=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_en', models.CharField(blank=True, max_length=100, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('name_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_entry', to='main.document')),
            ],
            options={
                'verbose_name_plural': 'document metadata',
                'ordering': ['source_filename'],
                'indexes': [models.Index(fields=['university'], name='main_docume_univers_48a8ea_idx'), models.Index(fields=['year', 'grade'], name='main_docume_year_bc1505_idx'), models.Index(fields=['name_code'], name='main_docume_name_co_118f0f_idx')],
            },
        ),
    ]
